Update TorrentTransfer to v1.6_添加分类识别转钟
jxxghp/MoviePilot-Plugins pull request #473
Opened 2024-10-01 17:26 UTC by shaoyangx

添加根据种子分类进行转种（无标签种子逻辑未更改）。
略微修饰UI对称。
判定顺序：
不需要转移的路径
种子分类
是否转移无标签种子
不转移标签
转移标签

2024-10-01 17:43 UTC, InfinityPacer requested changes

2024-10-01 17:43 UTC, InfinityPacer commented on plugins/torrenttransfer/__init__.py
> +            return []
数据结构有问题，也未能支持配置多个转移分类

2024-10-01 19:36 UTC, shaoyangx commented on plugins/torrenttransfer/__init__.py
> +            return []
最终return类型应该为()，已修改。
多分类转移支持，和标签规则一致，按照 , 分割，详细可看代码633行。

2024-10-02 05:06 UTC, shaoyangx commented on plugins/torrenttransfer/__init__.py
> +            return []
> 数据结构有问题，也未能支持配置多个转移分类

我昨晚修改的好像不太对，我查看他返回的是any
我以前只写过自己需求的代码，对数据类型的要求并没有仔细确认过，今天看了一下，是否应该写成以下这样才算正确。以下返回的是仅str
```python
    def __get_category(torrent: Any, dl_type: str):
        """
        获取种子分类
        """
        try:
            return (str(torrent.get("category").strip())) \
                if dl_type == "qbittorrent" else ''
        except Exception as e:
            print(str(e))
            return ''
```

2024-10-02 06:31 UTC, InfinityPacer commented on plugins/torrenttransfer/__init__.py
> +            return []
1. `()` 在Python中代表元组，用元组包括一个字符串，但因为只有一个元素，而且没有逗号，所以此时不是元组，实际上就是一个字符串。
2. 假设种子分类是`测试1`，配置的转移分类为`测试分类1`，在你目前的代码中也能命中，这是错误的
3. 转移分类假设为`测试分类1,测试分类2`，应该通过`split`进行分割，然后在使用`in`，此外，使用`split`前，建议进行容错处理
4. 最后，建议学习一下Python基本语法

2024-10-02 11:09 UTC, shaoyangx commented on plugins/torrenttransfer/__init__.py
> +            return []
已解决。（许久未用基本数据类型都忘干净了）

2024-10-02 11:47 UTC, closed without merging

2024-10-02 11:50 UTC, shaoyangx commented
本地提交莫名错乱了，重新PR